// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SupportWheelOfFate.Database;
using System;

namespace SupportWheelOfFate.Database.Migrations
{
    [DbContext(typeof(SupportWheelContext))]
    [Migration("20180108164718_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupportWheelOfFate.Domain.Models.Engineer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("SupportWheelOfFate.Domain.Models.ScheduleEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<long>("EngineerId");

                    b.Property<int>("Shift");

                    b.HasKey("Id");

                    b.HasIndex("EngineerId");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("SupportWheelOfFate.Domain.Models.ScheduleEntry", b =>
                {
                    b.HasOne("SupportWheelOfFate.Domain.Models.Engineer", "Engineer")
                        .WithMany()
                        .HasForeignKey("EngineerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
